language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
branches:
  only:
    - master
before_install: gem update --remote bundler
before_script:
  - "sh -c 'cd spec/dummy && RAILS_ENV=test bundle exec rake db:schema:load'"
script: "bundle exec rake spec"
